services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: etercloud-app
    ports:
      - "8080:80"
    environment:
      - APP_KEY=${APP_KEY}
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE:-laravel}
      - DB_USERNAME=${DB_USERNAME:-sail}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - RUN_MIGRATIONS=true
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/vendor
      - /app/node_modules
      - /app/public/build

  db:
    image: mysql/mysql-server:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-password}
      - MYSQL_ROOT_HOST='%'
      - MYSQL_DATABASE=${DB_DATABASE:-laravel}
      - MYSQL_USER=${DB_USERNAME:-sail}
      - MYSQL_PASSWORD=${DB_PASSWORD:-password}
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD:-password}"]
      retries: 3
      timeout: 5s

volumes:
  mysql-data:
